branches:
  only:
  - master

dist: xenial
language: python
python:
  - 3.7
  - 3.8
before_install:
  - pip install poetry
install:
  - poetry install
# before_script:
#   - sudo snap install microk8s --classic --channel=1.14/stable
#   - sudo microk8s.status --wait-ready
#   - sudo microk8s.kubectl config view --raw > $HOME/microk8s.conf
script:
  - mypy k8s_jobs test
  - pytest
  # - TEST_K8S_CONFIG_PATH=$HOME/microk8s.conf pytest -m k8s_itest
