apiVersion: v1
kind: ConfigMap
metadata:
  name: helloworld
  labels:
    app: job-server
data:
  helloworld: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: helloworld
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: ubuntu
            command: ["echo", "helloworld"]
          restartPolicy: Never
      backoffLimit: 0
      activeDeadlineSeconds: 600
