apiVersion: v1
kind: ConfigMap
metadata:
  name: job-definitions
  labels:
    app: job-server
data:
  # This will be the filename under the mounted configmap
  job_definitions: |
    - name: helloworld
      # Note that this must be kept in sync with the actual mounted path
      spec_path: /etc/config2/helloworld-job-definition
    - name: helloworld-via-configmap
      spec_config_map_name: helloworld
      spec_config_map_namespace: default
    - name: fail
      spec: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: fail
        spec:
          template:
            spec:
              containers:
              - name: fail
                image: ubuntu
                command: ["/bin/sh"]
                args: ["exit", "1"]
              restartPolicy: Never
          backoffLimit: 0
          activeDeadlineSeconds: 600
    - name: timeout
      spec: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: timeout
        spec:
          template:
            spec:
              containers:
              - name: timeout
                image: ubuntu
                command: ["/bin/sh"]
                args: ["sleep", "1000"]
              restartPolicy: Never
          backoffLimit: 0
          activeDeadlineSeconds: 10
    - name: template
      spec: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: {{ name }}
        spec:
          template:
            spec:
              containers:
              - name: {{ name }}
                image: ubuntu
                command: ["echo", "{{ name }}"]
              restartPolicy: Never
          backoffLimit: 0
          activeDeadlineSeconds: 600
