apiVersion: v1
kind: ConfigMap
metadata:
  name: job-definitions
  labels:
    app: job-server
data:
  # List of job-definitions. Currently objects so that we can add more configuration in the future
  # if need be.
  job_definitions: |
    - name: pi
    - name: fail
    - name: timeout
    - name: template
  # Each job_definition must have a job configuration under the key specified by its name.
  pi: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: pi
    spec:
      template:
        spec:
          containers:
          - name: pi
            image: perl
            command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
          restartPolicy: Never
      backoffLimit: 0
      activeDeadlineSeconds: 600
  fail: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: fail
    spec:
      template:
        spec:
          containers:
          - name: fail
            image: ubuntu
            command: ["/bin/sh"]
            args: ["exit", "1"]
          restartPolicy: Never
      backoffLimit: 0
      activeDeadlineSeconds: 600
  timeout: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: timeout
    spec:
      template:
        spec:
          containers:
          - name: timeout
            image: ubuntu
            command: ["/bin/sh"]
            args: ["sleep", "1000"]
          restartPolicy: Never
      backoffLimit: 0
      activeDeadlineSeconds: 10
  template: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: {{ name }}
    spec:
      template:
        spec:
          containers:
          - name: {{ name }}
            image: ubuntu
            command: ["echo", "{{ name }}"]
          restartPolicy: Never
      backoffLimit: 0
      activeDeadlineSeconds: 600
