apiVersion: batch/v1
kind: Job
metadata:
  name: {{ templatevar }}
spec:
  template:
    spec:
      containers:
      - name: {{ templatevar }}
        image: ubuntu
        command: ["echo", "{{ templatevar }}"]
      restartPolicy: Never
  backoffLimit: 0
  activeDeadlineSeconds: 600
