apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
      - name: hello
        image: ubuntu
        command: ["echo", "hello"]
      - name: world
        image: ubuntu
        command: ["echo", "world"]
      restartPolicy: Never
  backoffLimit: 0
  activeDeadlineSeconds: 600
