---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-manager
rules:
- apiGroups: ["batch"]
  resources:
    - "jobs"
  verbs: ["create", "get", "list", "delete"]
- apiGroups: ["batch"]
  resources:
    - "jobs/status"
  verbs: ["get", "list"]
- apiGroups: [""]
  resources:
    - "pods"
  verbs: ["get", "list"]
- apiGroups: [""]
  resources:
    - "pods/log"
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: job-server
subjects:
- kind: ServiceAccount
  name: job-server
  namespace: default
roleRef:
  kind: ClusterRole
  name: job-manager
  apiGroup: rbac.authorization.k8s.io
